#apiVersion: v1
#kind: Service
#metadata:
#  # namespace: my-namespace
#  labels:
#    app: cuda-test-svc
#  name: cuda-test-svc
#spec:
#  ports:
#  - name: http
#    port: 8888
#    targetPort: 8888
#    protocol: TCP
#  selector:
#    app: cuda-test-svc
#---
kind: Job
apiVersion: batch/v1
metadata:
  name: cuda-test-svc
  # namespace: my-namespace
spec:
  template:
    metadata:
      labels:
        app: cuda-test-svc
    spec:
      tolerations:
      - key: gpu
        operator: "Equal"
        value: "true"
      tolerations:
        - key: gpu
          operator: "Equal"
          value: "true"
      restartPolicy: Never
      imagePullSecrets:
        - name: gitlab-cuda-svc
      containers:
        - name: cuda-test-svc
          image: docker-hub.informatik.haw-hamburg.de/mars/mars-cuda-nn3d/cuda-test-svc:dev 
          imagePullPolicy: Always
          resources:
            limits:
              nvidia.com/gpu: 1
          ports:
          - containerPort: 8888
            name: http
            protocol: TCP
